version: '3.8'

services:
  # MySQL service
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_vol:/var/lib/mysql

  # Rails application service
  rails:
    build: .
    container_name: rails
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      RAILS_ENV: development # production
      RAILS_MASTER_KEY: 61def8862ea958c3301eb21c807cae0e
      ES_PORT: 9200
      ES_HOST: 'elasticsearch'
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      REDIS_URL: redis://redis:6379/1
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
    volumes:
      - ./:/rails
      - /rails/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch
    links:
      - db
      - sidekiq
      - elasticsearch

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - node.name=es
      - cluster.name=cluster
      - discovery.seed_hosts=es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.port=9200
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_vol:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
    depends_on:
      - db

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - db
    volumes:
      - redis_vol:/data

  # Sidekiq worker
  sidekiq:
    build: .
    command: "bundle exec sidekiq"
    container_name: sidekiq
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      RAILS_ENV: development
      ES_PORT: 9200
      ES_HOST: 'elasticsearch'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis
    volumes:
    - ./:/rails   # I really hate hate docker >:(


volumes:
  mysql_vol:
  es_vol:
  redis_vol:
