version: '3.8'

services:
  # MySQL service
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
        timeout: 20s
        retries: 10

  # Rails application service
  rails:
    build: .
    container_name: rails
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    restart: always
    volumes:
      - ./:/rails
      - /rails/tmp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db